name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: cache-maven-repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repository

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: setup-firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1.7.0

      - name: setup-geckodriver
        uses: browser-actions/setup-geckodriver@latest

      - name: build
        env:
          FIREFOX_PATH: ${{ steps.setup-firefox.outputs.firefox-path }}
        run: mvn -B clean verify

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/*.jar
